### PR TITLE
Turn off force source handling in prompt processing default

### PR DESCRIPTION
**Pull request by hsinfang**
I'm turning it off as the `dev` default too, so it's getting tested by default.

### CODE REVIEW

**Review by kfindeisen — APPROVED** [review]
I'm not sure about turning it off in `dev`, but it's untestable either way (LATISS is too small, and ComCamSim doesn't have templates). As long as we don't forget to remove those later...

**Comment by hsinfang** [comment]
Do it more properly with a ticket in https://github.com/lsst-sqre/phalanx/pull/3150

**Comment by hsinfang** [comment]
Actually I've added templates for ComCamSim in dev.  

I'll edit and not change in `dev` then.  

Sorry for the change of mind about ticket.

**Comment by hsinfang** [comment]
> Actually I've added templates for ComCamSim in dev.
But the templates I added don't seem to cover the raw.  

... I will refresh the dev raw then. But probably not today.

**Pull request closed without merging**
