### PR TITLE
deploy usdfint environment

### PR DESCRIPTION
**Pull request by pav511**
- rest-proxy disabled in sasquatch
- livetap/ssotap image repo set to usdf-prod
- nublado proxy-connect timeouts set high to test web socket timeouts

### CODE REVIEW

**Review by athornton — CHANGES_REQUESTED** [review]
I would recommend dropping cachemachine and moneypenny from the environment file completely, and removing the cachemachine, moneypenny, and nublado2 values files as well.  Having the application config file not be present is an easier indicator of whether an application exists in a given environment than having to go look it up over in the environment config.

**Comment by pav511** [comment]
Removed files for nublado2/moneypenny/cachemachine for usdfint.
I also removed the extended proxy-connect-timeout from nublado since it doesn't appear to be a phalanx related config issue.

**Review by athornton — APPROVED** [review]
LGTM

**Comment by pav511** [comment]
Great!
quick rebase on main then I'll merge

**Pull request merged**
