### PR TITLE
DM-33922: Update exposurelog and narrativelog

### PR DESCRIPTION
**Pull request by r-owen**
Update for new versions of both packages.
Move chart and template files from the charts package to this package.

### CODE REVIEW

**Review by athornton — APPROVED** [review]
LGTM

**Review by athornton — CHANGES_REQUESTED** [review]
YAML linter is angry; check indentation.

**Comment by r-owen** [comment]
Thanks for pointing that out. I messed up the updates on a few site-specific files by dropping the leading `exposurelog:`. Fixed and I also modernized exposurelog/values-roe.yaml (the last of the site-specific value files).

**Review by athornton — APPROVED** [review]
LGTM pending rebase against current master.

**Pull request merged**
